name: Automatic Course Grabbing

# on:
#   workflow_dispatch:
#   schedule:
#    - cron: '00 00 * * *' # 抢课时间
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Auto Daily Attendance
        env:
          STUDENT_ID: ${{ secrets.STUDENT_ID }}
          PASSWORD: ${{ secrets.PASSWORD }}
          COURSE_ID : ${{ secrets.COURSE_ID }}
        run: python AutomaticCourseGrabbing.py
